name: CI - Playwright

on:
  push:
    branches: [ "main, Master" ]
  pull_request:
  branches: [ "main, Master" ]


jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Instalar navegadores y librerías del sistema
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Ejecutar pruebas de Playwright

      - name: Run Playwright Tests
        run: npx playwright test --reporter=html --reporter=dot --output=playwright-report --trace on-first-retry --config=playwright.config.js
        env:
          # Define tus variables de entorno necesarias aquí
          BASE_URL: ${{ secrets.BASE_URL }} # Asegúrate de definir BASE_URL en los secretos del repo


      # Publica artefactos (reportes, screenshots, videos, traces)
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-${{ matrix.browser }}
          path: |
            playwright-report/**
            test-results/**
          if-no-files-found: ignore
